### ISSUE TITLE
Sorting arrays with objects

### ISSUE THREAD

**Issue by carecki** [ShivrajRath/jsonabc#1]
There is an issue in your code, regarding sorting arrays that contain objects.
It could be fixed by firstly sorting those objects recursively, and then sorting array of them. Sorting array could be done by comparing json representation of each object.

Here is the fixed sortJSON function:
```javascript
        function sortJSON(un) {
            if (isArray(un)) {
                var or = new Array();
                un.forEach(function(v, i) {
                    or[i] = sortJSON(v);
                });
                or = or.sort(function (a, b) {
                    a =  JSON.stringify(a);
                    b =  JSON.stringify(b);
                    return a < b ? -1 : (a > b ? 1 : 0);
                });
                return or;
            } else if (isPlainObject(un)) {
                var or = {};
                Object.keys(un).sort().forEach(function(key) {
                    or[key] = sortJSON(un[key]);
                });
                return or;
            }

            return un;
        }
```

**Comment by ShivrajRath** [comment]
Can you please give an example, where the current code failed?

**Comment by carecki** [comment]
Well, the simplest example would be to try sorting following json:
```
[
	{ "a" : 1, "b" : 1},
	{ "b" : 2, "a" : 2}
]
```
And then try to sort the same, but with two rows swapped:
```
[
	{ "b" : 2, "a" : 2},
	{ "a" : 1, "b" : 1}
]
```
The result of sorting generates two different jsons. But it should be the same in these two cases.

**Comment by ShivrajRath** [comment]
This should be fixed in the latest build.
