### ISSUE TITLE
Should arrays be sorted?

### ISSUE THREAD

**Issue by mtahirtariq** [ShivrajRath/jsonabc#2]
I believe (at least according to the API responses I have worked with) only dict keys should be sorted not the arrays. As sometimes, order of arrays matter for the end user and by sorting it is messed up. Or at least it should be optional. Any thoughts???

**Comment by ShivrajRath** [comment]
Thanks for the suggestion. I've added an option to ignore sorting of plain arrays. Kindly check if it helps [novicelab.org/jsonabc/](novicelab.org/jsonabc/)
