### ISSUE TITLE
upper case not alphabetical

### ISSUE THREAD

**Issue by evbo** [ShivrajRath/jsonabc#23]
Got incorrect result when all caps is used:
```json
{
    "a": [
        {
            "label": "AT"
        },
        {
            "label": "Ag"
        }
    ]
}
```

**Comment by ShivrajRath** [comment]
Hi @evbo, are you expecting sorting on the value and not on the keys? If so, the current sorting happens only on the keys. Can you please post the result you were expecting?

**Comment by evbo** [comment]
thanks I thought it was sorting values my mistake. Feel free to close if that's not what you were intending.
