### ISSUE TITLE
Sorting improvement for more complicated jsons

### ISSUE THREAD

**Issue by DariuszKa** [ShivrajRath/jsonabc#3]
I need to compare and find differences in two attached json files.
To do so sorting is really crucial. Problem with all comparers available (not only http://novicelab.org/jsonabc/ or http://jsoneditoronline.org/ but also http://json-diff.com/) is that sorting or ignoring order works only for some depth properly.
[jsons.zip](https://github.com/ShivrajRath/jsonabc/files/1159416/jsons.zip)

**Comment by ShivrajRath** [comment]
I think sorting would work fine to significant depths. However, there was a issue with sorting with case, which I've fixed. Could you see if that helps in your case?
