### ISSUE TITLE
case insensitive sorting

### ISSUE THREAD

**Issue by pepepaco** [ShivrajRath/jsonabc#4]
I think the case for sorting should be ignored, otherwise we get something like this:
        "Admin": {
            "ALREADY_EXISTS": "Already Exists",
            "INVALID_DATA": "Invalid Data",
            "Users": "Users",
            "addUsers": "Add User",
            "btnClose": "Close",
            "userPopUpTitle": "Edit user",
            "user_Name": "Email"
        }
or at least give the option to disable it. thanks.

**Comment by ShivrajRath** [comment]
Thanks for bringing this one. Have fixed this one in latest commit. Kindly verify: [http://novicelab.org/jsonabc/](http://novicelab.org/jsonabc/)
