### ISSUE TITLE
Standalone fails without net connection

### ISSUE THREAD

**Issue by AugustM** [ShivrajRath/jsonabc#8]
I appreciate that your utility can be run standalone, but I am disturbed that a standalone function is calling Google Analytics and Google Syndication. I get error messages if I am not connected to the net. That kind of defeats the concept of "standalone".

Could you please identify if your utility is actually dependent on any of those external sites?

Thanks.

**Comment by ShivrajRath** [comment]
In the latest version, the demo app logic is removed from the core logic. Core logic is published as npm library for reusability and standalone purpose.
